### ISSUE TITLE
PPI is active on A5 = LOW

### ISSUE THREAD

**Issue by siriokds** [silvervest/mitec2#1]
The SC-3000 PPI /CS signal is directly connected to A5, This is why you can't use any ports with A5 = 0.

**Comment by silvervest** [comment]
Very good point, I've documented that PPI is "activated" by /IORQ, but really it should say that the /RD /WR pins of the PPI are activated.

Thanks!

**Comment by siriokds** [comment]
> Very good point, I've documented that PPI is "activated" by /IORQ, but really it should say that the /RD /WR pins of the PPI are activated.
> 
> Thanks!

A6 and A7 set to "high" probably means "everything but the internal chip selection". PPI is selected but never used on that port. IOR and IOW are used for cartridge connected devices (strangely SF-7000 doesn't use it but rebuild the IOR/IOW internally)...

My schematic can help to clarify what I mean:

![FB_IMG_1670215912038](https://user-images.githubusercontent.com/7480736/205552469-920208fb-194a-4fdb-89c2-8b92e515c4a2.jpg)
